### ISSUE TITLE
Hashing feature flag doesn't work on targets without AES intrinsics

### ISSUE THREAD

**Issue by Veritius** [Veritius/bevy_stardust#31]
gxhash requires AES-NI and SSE2 intrinsics on x86-64 and AES and NEON intrinsics on ARM. Without these, it won't compile, since there's no fallback for processors lacking these intrinsics. Since gxhash is used in the `hashing` feature flag, any project using Stardust with this flag will suffer from compile failures.
Tracking issue for a fallback is here: https://github.com/ogxd/gxhash/issues/47

**Comment by omkarium** [comment]
Is there a solution to this? I am passing -C target-feature=aes but rust docs are failing

**Comment by Veritius** [comment]
> Is there a solution to this? I am passing -C target-feature=aes but rust docs are failing

I'm not sure, you'd have to ask the author of gxhash.
